[input]
base_directory = "output"
html_selector = "main"

[[input.files]]
path = "pages/about.html"
url = "/pages/about.html"
title = "About"

[[input.files]]
path = "pages/people.html"
url = "/pages/people.html"
title = "People"

[[input.files]]
path = "pages/publications.html"
url = "/pages/publications.html"
title = "Publications"

[[input.files]]
path = "pages/research.html"
url = "/pages/research.html"
title = "Research"

[[input.files]]
path = "paper-accepted-in-aiaa-scitech.html"
url = "/paper-accepted-in-aiaa-scitech.html"
title = "Paper accepted in AIAA SciTech"

[[input.files]]
path = "paper-accepted-in-ieee-access.html"
url = "/paper-accepted-in-ieee-access.html"
title = "Paper accepted in IEEE Access"

[[input.files]]
path = "paper-accepted-in-ieee-transactions-on-industrial-informatics.html"
url = "/paper-accepted-in-ieee-transactions-on-industrial-informatics.html"
title = "Paper accepted in IEEE Transactions on Industrial Informatics"

[[input.files]]
path = "paper-accepted-in-iftomm-asian-conference-on-mechanism-and-machine-science.html"
url = "/paper-accepted-in-iftomm-asian-conference-on-mechanism-and-machine-science.html"
title = "Paper accepted in IFToMM Asian conference on Mechanism and Machine Science"